# Generated by Django 5.0 on 2024-01-08 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labor', '0003_labor_register_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='parties_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('firm_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('labor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor.labor_register')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('total_payment', models.FloatField()),
                ('task_status', models.CharField(blank=True, choices=[('Pending', 'Task Pending'), ('Ongoing', 'Task On-Going'), ('Done', 'Task Done')], default='Pending', max_length=50)),
                ('paid_payment', models.FloatField(blank=True, default=0)),
                ('remaining_payment', models.FloatField(blank=True)),
                ('payment_status', models.CharField(blank=True, choices=[('Pending', 'Payment Pending'), ('Done', 'Payment Done'), ('Partially Paid', 'Partially Paid')], default='Pending', max_length=50)),
                ('labor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor.labor_register')),
                ('party_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.parties_detail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='payment_installment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('payment_entry', models.FloatField(default=0)),
                ('labor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor.labor_register')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
